apiVersion: v1
kind: Pod
metadata:
  name: mulesoft
  labels:
    app: mulesoft
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "mulesoft"
    vault.hashicorp.com/agent-inject-secret-credentials.txt: "secret/mulesoft/config"
spec:
  serviceAccountName: internal-app
  containers:
    - name: mulesoft
      image: jweissig/app:0.0.1
