apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-local-storage
  hostPath:
    path: "/var/lib/data"